<?php

return [
    'button' => '<button class="btn btn-default"{{attrs}}>{{text}}</button>',
    'checkbox' => '<input type="checkbox" name="{{name}}" value="{{value}}"{{attrs}}>',
    'checkboxFormGroup' => '<div class="">{{label}}</div>',
    'checkboxWrapper' => '<div class="checkbox ">{{label}}</div>',
    'dateWidget' => '{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}{{meridian}}',
    'error' => '<div class=""><div class="alert alert-danger">{{content}}</div></div><div class="clearfix"></div>',
    'errorList' => '<ul>{{content}}</ul>',
    'errorItem' => '<li>{{text}}</li>',
    'file' => '<input type="file" name="{{name}}"{{attrs}}>',
    'fieldset' => '<fieldset>{{content}}</fieldset>',
    'formStart' => '<div class="wb-frmvld wb-init"><form class="wetkit-form"{{attrs}} novalidate="novalidate">',
    'formEnd' => '</form></div>',
    'formGroup' => '{{label}}{{input}}',
    'hiddenBlock' => '<div style="display:none;">{{content}}</div>',
    'input' => '<input type="{{type}}" name="{{name}}" class="form-control"{{attrs}}>',
    'inputSubmit' => '<input class="btn btn-primary" type="{{type}}"{{attrs}}>',
    'inputContainer' => '<div class="input form-group {{type}}{{required}}">{{content}}</div>',
    'inputContainerError' => '<div class="input {{type}}{{required}} has-error error">{{content}}{{error}}</div>',
    'label' => '<label class="label-'.\Cake\Core\Configure::read("wetkit.lang").'" {{attrs}}>{{text}}</label>',
    'nestingLabel' => '{{hidden}}<label{{attrs}}>{{input}}{{text}}</label>',
    'legend' => '<legend>{{text}}</legend>',
    'option' => '<option value="{{value}}"{{attrs}}>{{text}}</option>',
    'optgroup' => '<optgroup label="{{label}}"{{attrs}}>{{content}}</optgroup>',
    'select' => '<div class=""><select name="{{name}}" class="form-control""{{attrs}}>{{content}}</select></div>',
    'selectMultiple' => '<div class=""><select name="{{name}}[]" class="form-control" multiple="multiple"{{attrs}}>{{content}}</select></div>',
    'radio' => '<input type="radio" name="{{name}}" value="{{value}}"{{attrs}}>',
    'radioWrapper' => '<div class="checkbox ">{{label}}</div>',
    'textarea' => '<div class=""><textarea name="{{name}}"{{attrs}} class="form-control">{{value}}</textarea></div>',
    'submitContainer' => '{{content}}',
];